import { z } from "zod";
import type { FastifyPluginAsync } from "fastify";
import {
  demoBehavioralRegressions,
  demoIntentContracts,
  demoSemanticGraph,
  demoServiceContracts,
  type MergeGateDecision,
  type SlackDigestPreview,
  type WebhookEvent
} from "@covenant/shared";
import { demoStore } from "../services/demo-store";

const githubWebhookSchema = z.object({
  event: z.string().min(1),
  repository: z.string().min(1),
  ref: z.string().min(1).default("refs/heads/main"),
  commitSha: z.string().optional()
});

const slackDigestSchema = z.object({
  channel: z.string().min(1).default("#covenant-alerts"),
  scope: z.enum(["security", "intent", "weekly"]).default("security")
});

const mergeGateSchema = z.object({
  prNumber: z.number().int().positive(),
  title: z.string().min(1),
  changedFiles: z.array(z.string()).default([])
});

export const platformRoutes: FastifyPluginAsync = async (app) => {
  app.get("/graph", async (request, reply) => {
    try {
      demoStore.assertOrganization(request.covenant.organizationId);
      return {
        graph: demoSemanticGraph,
        counts: {
          nodes: demoSemanticGraph.nodes.length,
          edges: demoSemanticGraph.edges.length,
          highRiskNodes: demoSemanticGraph.nodes.filter((n) => n.riskScore >= 70).length
        }
      };
    } catch {
      return reply.notFound("Organization not found");
    }
  });

  app.post("/integrations/github/webhook", async (request, reply) => {
    try {
      demoStore.assertOrganization(request.covenant.organizationId);
      const body = githubWebhookSchema.parse(request.body ?? {});
      const accepted: WebhookEvent = {
        id: `webhook_${Date.now()}`,
        receivedAt: new Date().toISOString(),
        source: "github",
        event: body.event,
        repository: body.repository,
        ref: body.ref,
        agentsTriggered: ["agent_01", "agent_04", "agent_06", "agent_07", "agent_11", "agent_16", "agent_20"],
        status: "accepted"
      };
      return reply.code(202).send(accepted);
    } catch (err) {
      if (err instanceof z.ZodError) return reply.badRequest("Invalid webhook payload");
      return reply.notFound("Organization not found");
    }
  });

  app.post("/integrations/slack/digest", async (request, reply) => {
    try {
      demoStore.assertOrganization(request.covenant.organizationId);
      const body = slackDigestSchema.parse(request.body ?? {});
      const preview: SlackDigestPreview = {
        channel: body.channel,
        title: body.scope === "weekly"
          ? "Covenant - Weekly executive summary"
          : body.scope === "intent"
          ? "Covenant - Intent drift alert"
          : "Covenant - Security digest",
        blocks: [
          { kind: "header", text: "Covenant digest" },
          { kind: "section", text: "20/20 agents reporting. 1 violated intent contract, 2 open behavioral regressions." },
          { kind: "section", text: "Top risk: $4,200/hr exposed by /api/payments/charge." },
          { kind: "context", text: "Generated by Covenant - dry-run preview, not posted." }
        ],
        scheduledAt: new Date().toISOString()
      };
      return preview;
    } catch (err) {
      if (err instanceof z.ZodError) return reply.badRequest("Invalid digest scope");
      return reply.notFound("Organization not found");
    }
  });

  app.post("/pr-checks", async (request, reply) => {
    try {
      demoStore.assertOrganization(request.covenant.organizationId);
      const body = mergeGateSchema.parse(request.body ?? {});

      const failingChecks: MergeGateDecision["failingChecks"] = [];
      const passingChecks: string[] = [];

      const violatedContract = demoIntentContracts.find((c) => c.status === "violated");
      if (violatedContract) {
        failingChecks.push({
          name: `Intent contract: ${violatedContract.name}`,
          severity: "high",
          message: violatedContract.plainEnglish
        });
      } else {
        passingChecks.push("All intent contracts passing");
      }

      const violatedSc = demoServiceContracts.find((c) => c.status === "violated");
      if (violatedSc) {
        failingChecks.push({
          name: `Service contract: ${violatedSc.consumerService} -> ${violatedSc.providerService}`,
          severity: "high",
          message: violatedSc.expectation
        });
      } else {
        passingChecks.push("All service contracts verified");
      }

      const recentRegression = demoBehavioralRegressions.find((r) => r.prNumber === body.prNumber);
      if (recentRegression) {
        failingChecks.push({
          name: `Behavioral regression`,
          severity: recentRegression.severity,
          message: `${recentRegression.contract} - ${recentRegression.before} -> ${recentRegression.after}`
        });
      } else {
        passingChecks.push("No behavioral regressions detected for this PR");
      }

      const decision: MergeGateDecision["decision"] = failingChecks.some((c) => c.severity === "critical" || c.severity === "high")
        ? "block"
        : failingChecks.length > 0
        ? "warn"
        : "allow";

      const result: MergeGateDecision = {
        prNumber: body.prNumber,
        decision,
        rationale:
          decision === "block"
            ? "Merge blocked: high-severity intent or contract violation detected."
            : decision === "warn"
            ? "Merge allowed with warnings."
            : "All merge gates green.",
        failingChecks,
        passingChecks,
        evaluatedAt: new Date().toISOString()
      };

      return result;
    } catch (err) {
      if (err instanceof z.ZodError) return reply.badRequest("Invalid PR check payload");
      return reply.notFound("Organization not found");
    }
  });
};
