import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { demoChangelog } from "@covenant/shared";

export const metadata = { title: "Changelog - Covenant" };

const riskTone: Record<string, string> = {
  info: "bg-mist text-graphite",
  low: "bg-teal/10 text-teal",
  medium: "bg-amber/10 text-amber",
  high: "bg-ember/10 text-ember",
  critical: "bg-ember text-white"
};

export default function ChangelogPage() {
  return (
    <main className="min-h-screen">
      <SiteHeader />
      <section className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
        <p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal">Changelog</p>
        <h1 className="mt-3 text-4xl font-bold text-ink sm:text-5xl">What's shipping.</h1>
        <p className="mt-4 max-w-2xl text-base leading-7 text-graphite/76">
          Three views per release: developer, founder, auditor. Auto-generated by Covenant's
          Changelog Narrator from real git commits.
        </p>

        <ol className="mt-10 space-y-5">
          {demoChangelog.map((entry) => (
            <li key={entry.id} className="rounded-panel border border-line bg-white p-6 shadow-crisp">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div>
                  <p className="text-xs font-semibold uppercase tracking-[0.16em] text-graphite/65">
                    {new Date(entry.date).toLocaleDateString(undefined, { dateStyle: "medium" })} - {entry.author}
                  </p>
                  <p className="mt-1 font-mono text-xs text-graphite/55">{entry.commitSha}</p>
                </div>
                <span className={`rounded-full px-3 py-1 text-[11px] font-bold uppercase tracking-[0.12em] ${riskTone[entry.riskTag] ?? "bg-mist text-graphite"}`}>
                  {entry.riskTag}
                </span>
              </div>
              <div className="mt-4 grid gap-4 sm:grid-cols-3">
                <div>
                  <p className="text-xs font-bold uppercase tracking-[0.14em] text-graphite/65">Developer</p>
                  <p className="mt-1 text-sm leading-6 text-ink">{entry.developerSummary}</p>
                </div>
                <div>
                  <p className="text-xs font-bold uppercase tracking-[0.14em] text-graphite/65">Founder</p>
                  <p className="mt-1 text-sm leading-6 text-ink">{entry.founderSummary}</p>
                </div>
                <div>
                  <p className="text-xs font-bold uppercase tracking-[0.14em] text-graphite/65">Auditor</p>
                  <p className="mt-1 text-sm leading-6 text-ink">{entry.auditorSummary}</p>
                </div>
              </div>
              <div className="mt-4 flex flex-wrap gap-2">
                {entry.affectedAreas.map((area) => (
                  <span key={area} className="rounded-full border border-line bg-paper px-3 py-1 text-xs font-semibold text-graphite">{area}</span>
                ))}
              </div>
            </li>
          ))}
        </ol>
      </section>
      <SiteFooter />
    </main>
  );
}
