#!/usr/bin/env node
/**
 * pnpm gen:agent <key> [<title>]
 *
 * Scaffolds a new analyzer agent at packages/analyzer/src/agents/<key>.ts
 * implementing the AgentContract. Idempotent — bails if the file
 * already exists.
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const ROOT = join(dirname(__filename), "..");

const [, , rawKey, ...titleParts] = process.argv;
if (!rawKey) {
  console.error("usage: pnpm gen:agent <key> [<title>]");
  process.exit(1);
}
const key = rawKey.replace(/[^a-z0-9-]/gi, "-").toLowerCase();
const title = titleParts.join(" ") || key.replace(/-/g, " ");
const className = key
  .split("-")
  .filter(Boolean)
  .map((p) => p[0].toUpperCase() + p.slice(1))
  .join("") + "Agent";

const target = join(ROOT, "packages", "analyzer", "src", "agents", `${key}.ts`);
if (existsSync(target)) {
  console.error(`refusing to overwrite ${target}`);
  process.exit(1);
}
mkdirSync(dirname(target), { recursive: true });

const body = `import type { AgentContext, AgentContract, AgentResult } from "../agent-contract";

/**
 * ${title} — generated by pnpm gen:agent ${key}.
 *
 * TODO: replace this stub with real analysis. The contract is:
 *   - Inspect ctx.repo / ctx.diff and emit findings.
 *   - Findings must be deterministic for a given input.
 *   - Side effects (network, fs writes) are forbidden.
 */
export const ${className}: AgentContract = {
  id: "${key}",
  title: "${title}",
  async run(ctx: AgentContext): Promise<AgentResult> {
    void ctx;
    return { findings: [] };
  }
};

export default ${className};
`;

writeFileSync(target, body, "utf8");
console.log(`created ${target}`);
