#!/usr/bin/env node
/**
 * pnpm gen:route <name>
 *
 * Scaffolds a new Fastify route plugin at apps/api/src/routes/<name>.ts
 * plus a matching node:test test file. Idempotent.
 */

import { existsSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const ROOT = join(dirname(__filename), "..");

const [, , rawName] = process.argv;
if (!rawName) {
  console.error("usage: pnpm gen:route <name>");
  process.exit(1);
}
const name = rawName.replace(/[^a-z0-9-]/gi, "-").toLowerCase();
const camel = name.replace(/-(.)/g, (_, c) => c.toUpperCase());
const exportName = `${camel}Routes`;

const route = join(ROOT, "apps", "api", "src", "routes", `${name}.ts`);
const test = join(ROOT, "apps", "api", "src", `${name}.test.ts`);
for (const p of [route, test]) {
  if (existsSync(p)) {
    console.error(`refusing to overwrite ${p}`);
    process.exit(1);
  }
}

const routeBody = `import type { FastifyPluginAsync } from "fastify";

/**
 * ${name} routes — generated by pnpm gen:route ${name}.
 *
 * Wire this into apps/api/src/app.ts:
 *   import { ${exportName} } from "./routes/${name}";
 *   app.register(${exportName}, { prefix: "/v1" });
 */
export const ${exportName}: FastifyPluginAsync = async (app) => {
  app.get("/${name}", async () => ({ ok: true, route: "${name}" }));
};
`;

const testBody = `import { test } from "node:test";
import assert from "node:assert/strict";
import { buildApp } from "./app";

test("GET /v1/${name} returns ok", async () => {
  const app = buildApp();
  const res = await app.inject({ method: "GET", url: "/v1/${name}" });
  assert.equal(res.statusCode, 200);
  const body = res.json() as { ok: boolean; route: string };
  assert.equal(body.ok, true);
  assert.equal(body.route, "${name}");
  await app.close();
});
`;

writeFileSync(route, routeBody, "utf8");
writeFileSync(test, testBody, "utf8");
console.log(`created ${route}`);
console.log(`created ${test}`);
console.log(`remember to register ${exportName} in apps/api/src/app.ts and add ${name}.test.ts to the test script.`);
